---
title: "The Role of Visualization in Abstract Mathematical Discovery"
subtitle: "Faculty of Arts and Science, University of Toronto"
author: "Cristina Burca"
thanks: "Code and data are available at: LINK."
abstract: " By examining Stott’s ability to visualize complex objects and how it led to groundbreaking insights, alongside Coxeter’s contributions that emphasized the necessity of formal proof and classification, this thesis argues the importance of visualization, especially in conceptualizing abstract structures that are beyond our immediate interpretation. While mathematics is largely empirical and reliant on provable notions, the necessity of intuitive and visual methods to establish an understanding of complex geometrical concepts greatly contributes to the formal mathematical methods in reaching a replicable understanding of complex geometric structures. To navigate to higher dimensions of mathematics, an intuitive approach is valuable in establishing a replicable understanding of complex geometric structures."
format: 
  pdf:
    documentclass: report
    geometry: margin = 1in
date: today
date-format: long
fontsize: 12pt
spacing: double
---


Faculty of Arts and Science, University of Toronto
MAT391: History of Mathematics after 1700
Professor Sylvia Nickerson
April 8, 2024

The exploration of polytope geometry and higher-dimensional spaces has long captivated the minds of scholars across generations, with many of its mysteries remaining undiscovered. This evolution, marked by significant contributors such as Alicia Boole Stott and Donald Coxeter, exemplifies an advancement in mathematical concepts, specifically in higher dimensional geometry and theory. From the methods of Stott, who conceptualized and built three-dimensional representations of four-dimensional shapes, to Coxeter’s analysis of the shapes based on their geometric properties, we witness a diversity and cooperation of strategies, from her intuitive visualizations to his formalistic approach. By examining Stott’s ability to visualize complex objects and how it led to groundbreaking insights, alongside Coxeter’s contributions that emphasized the necessity of formal proof and classification, this thesis argues the importance of visualization, especially in conceptualizing abstract structures that are beyond our immediate interpretation. While mathematics is largely empirical and reliant on provable notions, the necessity of intuitive and visual methods to establish an understanding of complex geometrical concepts greatly contributes to the formal mathematical methods in reaching a replicable understanding of complex geometric structures. To navigate to higher dimensions of mathematics, an intuitive approach is valuable in establishing a replicable understanding of complex geometric structures.

Humans possess natural spatial understanding, stimulating the conceptualization of abstract ideas, particularly when working with intangible principles that become hard to quantify. Consider the instance of Newton and the falling apple – this observation prompted him to investigate and define the fundamental causation for the apple's fall, thus exemplifying how tangible theories can instigate pursuits of deeper understanding. Introduced to the concept of complex geometric models by her brother-in-law, Alicia Boole Stott utilized an intuitive understanding of complex geometry rather than a formal approach that stemmed from the teachings of her mother and personal interest alone, due to the lack of educational opportunity offered for women at the time. Much like Newton, Stott’s unconventional work on polytopes came from her exceptional ability to visualize complex shapes, indicating the importance of intuitive insight in early mathematical discoveries. She proved the existence of the six regular four-dimensional polytopes, and devised their visualizations by calculating the three-dimensional sections for polytopes to construct their models in cardboard. Stott used the idea that Platonic solids can be unfolded on a two-dimensional plane, and thus four-dimensional polytope can be broken down into its three-dimensional counterparts (Polo Blanco, 2014, p.151). Her physical models concurred with Pieter Hendrik Schoute's central section analytic calculations of the six regular polytopes (Polo Blanco & Rogora, 2014, p.157). Schoute could not understand how Stott found the sections without using established analytic methods, but was so impressed that he proposed further cooperative investigations of four-dimensional geometry, and spent many summers publishing joint mathematical findings (Mee, 2020, p.217). Donald Coxeter commented on Stott’s power of geometric visualization, which “supplemented Schoute’s more orthodox methods” (Chas, 2019, p.11) – implying that Schoute’s approach was more conventional, while Stott was merely complementing his work. However, her intuitive visualization allowed her to discover patterns and connections within the vertices and sections of polytopes when working with Schoute and Coxeter. She further discovered new processes such as constructing new polytopes from existing ones, by applying the principle of the golden section: where instead of dividing the edges of the object in half, they were to be divided by the ratio of the golden section (Coxeter, 1935,  p.338). Stott also introduced the notion of partial truncation that led to the discovery of several uniform polytopes: the process that removes alternate vertices of a polytope, previously discussed analytically by Schoute (Coxeter, 1973, p.119). Her methods led to other significant connections, such as a way to study how a polytopes’ volume is distributed across its dimensions, and exploration of the combined relationships between polytopes and hyperplane sections (Polo Blanco, 2014, p.152). Through her work, Stott challenged the conventional standards of her time and contended that progressive mathematical insight does not necessarily stem from formal training or analytical methodologies, rather, it can emerge through intuitive visualization. Certain concepts are inherently difficult to grasp through analytical methods alone, and her approach highlighted the fundamental reliance humans have on spatial processing for understanding abstract concepts. Stott's work demonstrates that tangible models are not just supplementary to mathematical understanding, but highly valuable. 

Though Alicia Boole Stott successfully applied her intuitive understanding to pioneer complex geometric models, Donald Coxeter's subsequent contributions demonstrated how formal mathematical proof could solidify these intuitive discoveries into universally accepted truths. Formalism and rigorous mathematical proof are fundamental for validating theorems and concepts, as well as quantifying concepts to establish these truths. Coxeter was a Platonist (1973), which is the belief that math exists independently of human thought, and theories are true or false independently of our knowledge. This belief motivated him to explore rigorous mathematical frameworks, analyzing polytopes and their symmetries systematically. He stressed the importance of fundamental principles and structures that determined geometric forms, as well as the intrinsic properties and relationships of these objects. Coxeter worked with Stott until her death and included many of their findings in his book “Regular Polytopes”, which focused on the study of regular polytopes in various dimensions by extending concepts of regular polygons/polyhedra to higher dimensions – similar to Stott’s method, but through a strictly analytical approach. He additionally introduced "Coxeter Groups," a rigorous classification for polytopes in all dimensions based on their symmetries. He also observed that there are only three families of regular polytopes in dimensions higher than four, alongside proving the uniqueness of the five Platonic solids in three dimensions. Later into his career, Coxeter wrote, 
 ...there is no evidence that a fourth dimension of space exists in any physical or metaphysical sense...We merely choose to enlarge the scope of Euclidean geometry by denying one of the axioms ("Two planes which have one common point have another"), and we establish consistency of the resulting abstract system...wherein a point is represented by an ordered set of four (or more) real numbers: Cartesian coordinates (1973, p.119). 
 This identifies the doubts that Coxeter had about his work, but established motivators to further explore the topic — this skepticism wasn’t driven by doubt, but a consideration of mathematical limitations. This skepticism might be unusual coming from Coxeter, as his Platonic belief suggests an openness to fourth-dimensional space existing beyond the conventional understanding of space and time that could be approximated through physical means. However, he emphasized that we can approach higher-dimensional Euclidean spaces in three ways: axiomatically, algebraically, or intuitively. While he deemed the first two methods as achievable (Rowe, 2004, p.27), Stott's perspective would argue that the third intuitive approach simplifies and deepens the understanding of such abstract ideas. Coxeter’s emphasis on formalism was not absent of intuition; he approached the visualization of higher-dimensional spaces "so far as is safe," being cautious of the limits of intuitive conception without formal proof — which revealed a strategic use of intuition as a complementary tool to guide formulation (1973, p.119).  However, the ambiguity of intuition is what led to uncertainty. With the imprecision of dimensional analogy, other experts such as Mikowski were led to misconception by assuming the fourth Euclidean dimension is time, which does not adhere to the Euclidean principles of physical space (Coxeter, 1973, p.119). Proof can be creative to a certain extent, as expanding the boundaries of what is possible in mathematics can only be performed under certain limitations, considering the logical standards of mathematical truth. Stott elegantly demonstrated the intuitive approach to fourth-dimensional geometry while acknowledging the mathematical limitations, through transcending mathematical limitations by envisioning shapes beyond conventional three-dimensional understanding. 

The comparison of Stott's intuitive visualizations and Coxeter's formalist approach reveals a more comprehensive understanding that intuition and visualization are not merely tools for conceptualization, but are valuable for the development of proof and theories. Coxeter’s Platonic view of mathematics hindered his innovative thinking regarding the fourth dimension, which he perceived strictly as an extension of geometry rather than purely conceptual. In contrast, Stott’s lack of formal training and unbiased perspective allowed her to formulate innovations rooted in the simplest fundamental axioms and her intuition — that formal methods alone might not have attained. The limitations and uncertainty encountered in strictly formal analysis, such as the ones Coxeter encountered in his work, highlight the necessity of tangible models and visual intuition to fully comprehend and articulate proofs for geometrical structures. Although analytic work such as Coxeter’s may not be inherently flawed, its development might be challenging due to its lack of quantifiable evidence, and could further compromise the reliability of subsequent findings. Basing mathematical exploration on tangible models allows for in-depth analysis of specific aspects that formalism can validate, showing the collaborative relationship between these approaches. Their complementary nature can facilitate a deeper understanding in the formation of abstract concepts and mathematical theory — and it is a fact that one cannot exist without the other — but humans have an intrinsic spatial understanding that is most productive when navigating complex and intangible concepts. 

The synergic nature of mathematical theory emerges by juxtaposing Alicia Boole Stott's intuitive visualizations with Donald Coxeter's formalist approach, that reaches beyond the opposition of intuition and formalism. Stott's insights—based on spatial understanding and visualization second to none in their time—make apparent the essentiality of intuition in the early stages of theoretical development. The role of intuition is significant for formalism to progress, to formulate our comprehension. The strict analytic framework and formal method of proof in which Coxeter utilizes enforces the formalism necessary for validation of mathematical theories, but can hinder unconventional thinking for ideas that are nearly incomprehensible. Taken together, both Stott and Coxeter’s legacies reflect the collaborative nature of mathematical inquiry, and how the delicate balance between intuitive and analytical thinking is essential to progress in the field. This thesis asserts that, while formal proof and classification have their place in determining universally recognized empirical truths, intuition and visualization, especially in understanding complex geometrical concepts, are valuable tools essential to navigate mathematics outside the realm of empirical data. However, the mathematical community continues to hold firm that these approaches are to be used symbiotically in order to navigate the intangibility of higher-dimensional geometry. This demonstrates the enduring importance of both Stott's and Coxeter's work in this area. Through their work, one is able to acknowledge that the path towards understanding the fine points of mathematical structures is not confined to a single method of thinking – rather, both approaches are indispensable to the cause of knowledge. 



References
Chas, M. (2019). The extraordinary case of the Boole family. Notices of the American Mathematical Society, 66(11). https://doi.org/10.1090/noti1996 
Coxeter, H. S. (1935). Wythoff’s construction for uniform polytopes. Proceedings of the London Mathematical Society, s2-38(1), 327–339. https://doi.org/10.1112/plms/s2-38.1.327
Coxeter, H. S. (1973). Regular polytopes. Dover Publications. 
Mee, N. (2020). Aunt Alice in Wonderland. In Celestial Tapestry: The Warp and Weft of Art and Mathematics (pp. 211–222). essay, Oxford University Press. https://doi.org/10.1093/oso/9780198851950.001.0001 
Polo Blanco, I. (2014). Alicia Boole Stott’s models of sections of Polytopes. Lettera Matematica, 2(3), 149–154. https://doi.org/10.1007/s40329-014-0065-x
Polo Blanco, I., & Rogora, E. (2014). Polytopes. Lettera Matematica, 2(3), 155–159. https://doi.org/10.1007/s40329-014-0064-y
Polo-Blanco, I. (2008). Alicia Boole Stott, a geometer in higher dimension. Historia Mathematica, 35(2), 123–139. https://doi.org/10.1016/j.hm.2007.10.008


